[package]
name = "socket-filter-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
# socket-filter-common = { path = "../socket-filter-common" }

aya-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "socket-filter"
path = "src/main.rs"
