[package]
name = "robust-valid-command"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "socket-filter"
path = "src/main.rs"
